language: node_js
node_js:
  - '4.0.0'
  - '5'
  - '6'
  - '7'
  - '8'
sudo: false
before_script:
  - "npm run compile"
script:
  - "npm run test:cov"
after_script: "npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"